apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-app-config
data:
  POSTGRES_DB: "book"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_SCHEMA: "bookstore"

---
apiVersion: v1
kind: Secret
metadata:
  name: bookstore-app-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # "postgres" base64 encoded
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # "password" base64 encoded