apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-app
  template:
    metadata:
      labels:
        app: bookstore-app
    spec:
      containers:
      - name: bookstore-api
        image: emaaddocker/python-app:0.0.8
        ports:
        - containerPort: 8000
#        envFrom:
#        - configMapRef:
#            name: bookstore-app-config
#        - secretRef:
#            name: bookstore-app-secrets
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: bookstore-app-config
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: bookstore-app-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: bookstore-app-config
              key: POSTGRES_PORT
        - name: POSTGRES_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: bookstore-app-config
              key: POSTGRES_SCHEMA
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: bookstore-app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstore-app-secrets
              key: POSTGRES_PASSWORD
        envFrom:
        - secretRef:
            name: bookstore-app-secrets
        - configMapRef:
            name: bookstore-app-config 