apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  type: NodePort
  selector:
    app: bookstore-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001




# kubectl port-forward service/bookstore-service 80:80
# while acessing it from local host

# so that i can forward traffic to cluster --> Pod
# Forwarding from 127.0.0.1:80 -> 8000
# Forwarding from [::1]:80 -> 8000